sudo: required
services:
    - docker

before_install:
    - docker build -t stefanofranzoni/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run stefanofranzoni/react-test npm test -- --coverage

after_success:
    - docker build -t stefanofranzoni/multi-client ./client
    - docker build -t stefanofranzoni/multi-nginx ./nginx
    - docker build -t stefanofranzoni/multi-server ./server
    - docker build -t stefanofranzoni/multi-worker ./worker

#login in Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push stefanofranzoni/multi-client
    - docker push stefanofranzoni/multi-nginx
    - docker push stefanofranzoni/multi-server
    - docker push stefanofranzoni/multi-worker

deploy:
    provider: elastickbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-104955053484
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
